# Generated by Django 3.0.5 on 2020-04-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='picture',
            field=models.ImageField(default='', upload_to='media/pictures'),
        ),
    ]
