# Generated by Django 3.0.5 on 2020-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='test',
            field=models.TextField(default=''),
        ),
    ]
